#! /usr/bin/env ruby

# This script runs appropriate imp instance
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 
# maybe it's inside its own imp directory
# >>> user@linux ~/test/imp $ ./imp
#
# also might be called from inside another
# >>> user@linux ~/test/imp/src/coding $ imp
#
# otherwise try ~/.config/imp
# >>> user@linux ~ $ imp
# 
# else error


main = '/src/main'
path = []

# inside it's own
path << __dir__ + main

# inside another
tmp = Dir.pwd
begin
  path << tmp + main
  tmp = File.dirname tmp
end until tmp == '/'

# default imp
path << ENV['HOME'] + '/.config/imp' + main

# get first valid path
bin = path.find do |i|
  File.file? i
end

# none valid
if bin.nil?
  $stderr.puts "can't find appropriate imp"
  exit 1
end

# get current arguments
args = ''
ARGV.each do |arg|
  args << ' ' << arg
end

# execute appropriate imp
exec(bin + args)
