#! /usr/bin/env ruby

# AURA git root etc.
$git = __dir__ + "/../"
$src = __dir__
$lib = "#$src/lib"

# require external libs
require 'optparse'
require 'fileutils'
require 'open3'
require 'net/http'
require 'open-uri'

# require internal libs
Dir["#$lib/*"].each do |file|
  require_relative file
end

# CTRL+C interrupt
Signal.trap('INT') { puts; exit 1 }

# initialize environment
Cycle.go! "env"

unless $env.todo

  exit if $env.dump? or $env.toor?

  $stderr.puts "provide (one) package as an argument!"
  exit 1

end

Cycle.go! "install"
exit
# load the lifecycle
if $env.find?
  require_relative "#$src/cycle/browse"
else
  require_relative "#$src/cycle/install"
end
