#! /usr/bin/env ruby

# imp main script

# imp git root etc.
$git = File.expand_path __dir__ + "/../"
$src = __dir__
$lib = "#$src/lib"

# don't do anything accidentally
exit if ARGV.none?

# require external libs
require 'fileutils'
require 'digest'
require 'open3'
require 'net/http'
require 'open-uri'

# require internal libs
Dir["#$lib/*"].each do |file|
  require_relative file
end

# CTRL+C interrupt
Signal.trap('INT') { puts; exit 1 }

Task*  "init"
Task*  "repo"
Task*[ "pull", Env["todo"] ]
